name:                fibonacci-performance
version:             0.1.0.0
github:              "MI-AFP/fibonacci-performance"
license:             BSD3
author:              "Marek Suchánek"
maintainer:          "suchama4@fit.cvut.cz"
copyright:           "2019 Marek Suchánek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MI-AFP/fibonacci-performance#readme>

dependencies:
- base >= 4.7 && < 5
- criterion
- weigh

library:
  source-dirs: src

executables:
  fib:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fibonacci-performance
